<?php

use Illuminate\Database\Seeder;

class restoseeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	DB::table('resto')->insert([
    		[
    				'Resto_Name' => 'Carls Junior Kertajaya',
    				'Resto_Description' => 'Tempat makan yang menyediakan makanan western seperti burger',
    				'Resto_Location' => 'Jalan Kertajaya',
    				'Resto_City' => 'Surabaya',
    				'Type' => 3,
    				'Price_Min' => 30000,
    				'Price_Max' => 200000,
    				'Hours_Start' => '08:00:00',
    				'Hours_Closed' => '23:00:00',
    				'Wifi' => 1,
    				'Reservation' => 1,
    				'Smoking_Area' => 0,
    				'Free_Parking' => 0,
    		],
    		[
    				'Resto_Name' => 'Bebek Pak JOSS', 
					'Resto_Description' => 'Restoran aneka olahan bebek goreng', 
					'Resto_Location' => 'Jl. Kertajaya 81',   
					'Resto_City' => 'Surabaya',
					'Type' => 3, 
					'Price_Min' => 20000, 
					'Price_Max' => 35000, 
					'Hours_Start' => '08:00:00', 
					'Hours_Closed' => '22:00:00', 
					'Wifi' => 0, 
					'Reservation' => 1, 
					'Smoking_Area' => 1, 
					'Free_Parking' => 1,
    		],
    		[
    				'Resto_Name' => 'Layar', 
					'Resto_Description' => 'Restauran Keluarga dengan konsep mediteranial', 
					'Resto_Location' => 'Jl. Sumbawa 133',
					'Resto_City' => 'Surabaya',
					'Type' => 1, 
					'Price_Min' => 25000, 
					'Price_Max' => 200000, 
					'Hours_Start' => '10:00:00', 
					'Hours_Closed' => '22:00:00', 
					'Wifi' => 1, 
					'Reservation' => 1, 
					'Smoking_Area' => 0, 
					'Free_Parking' => 0,
    		],
    		[
    				'Resto_Name' => 'Primarasa', 
					'Resto_Description' => 'Restauran Ayam Bakar', 
					'Resto_Location' => 'Jl. Ahmad Yani',   
					'Resto_City' => 'Surabaya',
					'Type' => 1, 
					'Price_Min' => 15000, 
					'Price_Max' => 65000, 
					'Hours_Start' => '08:00:00', 
					'Hours_Closed' => '20:00:00', 
					'Wifi' => 0, 
					'Reservation' => 1, 
					'Smoking_Area' => 0, 
					'Free_Parking' => 1,
    		],
    		[
    				'Resto_Name' => 'Moru-Moru', 
					'Resto_Description' => 'Cafe remaja yang menyediakan berbagai dessert lucu dan menarik', 
					'Resto_Location' => 'Jl. Kemang',   
					'Resto_City' => 'Jakarta',
					'Type' => 3, 
					'Price_Min' => 25000, 
					'Price_Max' => 100000, 
					'Hours_Start' => '10:00:00', 
					'Hours_Closed' => '20:00:00', 
					'Wifi' => 1, 
					'Reservation' => 0, 
					'Smoking_Area' => 0, 
					'Free_Parking' => 0,
    		],
    		[
    				'Resto_Name' => 'La Pissa', 
					'Resto_Description' => 'Restauran Itali menyediakkan berbagai varian meu khas Itali dengan harga cafe', 
					'Resto_Location' => 'Jl. Mampang Prapatan',
					'Resto_City' => 'Jakarta',
					'Type' => 3, 
					'Price_Min' => 35000, 
					'Price_Max' => 150000, 
					'Hours_Start' => '09:00:00', 
					'Hours_Closed' => '23:30:00', 
					'Wifi' => 1, 
					'Reservation' => 1, 
					'Smoking_Area' => 0, 
					'Free_Parking' => 1,
    		],
    		[
    				'Resto_Name' => 'Mie Setan', 
					'Resto_Description' => 'Warung mie dan dimsum pedas dengan tingkatan level kepedasan beragam', 
					'Resto_Location' => 'Jl. Semolowaru 111',
					'Resto_City' => 'Surabaya',
					'Type' => 3,
					'Price_Min' => 10000, 
					'Price_Max' => 40000, 
					'Hours_Start' => '10:00:00', 
					'Hours_Closed' => '23:00:00', 
					'Wifi' => 1, 
					'Reservation' => 1, 
					'Smoking_Area' => 1, 
					'Free_Parking' => 0,
    		],
    		[
    				'Resto_Name' => 'Crazy Crab', 
					'Resto_Description' => 'Restoran yang menyediaakan berbagai olahan Seafood dengan menu andalan kepiting', 
					'Resto_Location' => 'Jl. Paris Van Java', 
					'Resto_City' => 'Bandung',
					'Type' => 1,
					'Price_Min' => 35000, 
					'Price_Max' => 200000, 
					'Hours_Start' => '11:00:00', 
					'Hours_Closed' => '22:00:00', 
					'Wifi' => 1, 
					'Reservation' => 1, 
					'Smoking_Area' => 0, 
					'Free_Parking' => 1,
    		],
    		[
    				'Resto_Name' => 'Bakso Mirna', 
					'Resto_Description' => 'warung bakso urat khas solo', 
					'Resto_Location' => 'Jl. Indramayu 333', 
					'Resto_City' => 'Bandung', 
					'Type' => 1, 
					'Price_Min' => 10000, 
					'Price_Max' => 30000, 
					'Hours_Start' => '09:30:00', 
					'Hours_Closed' => '22:00:00', 
					'Wifi' => 0, 
					'Reservation' => 0, 
					'Smoking_Area' => 1, 
					'Free_Parking' => 1,
    		],
    		[
    				'Resto_Name' => 'Warunk Upnormal', 
					'Resto_Description' => 'Tempat jual mie kekinian dan minuman enak', 
					'Resto_Location' => 'Jl. Bandung Lautan Api', 
					'Resto_City' => 'Bandung', 
					'Type' => 3, 
					'Price_Min' => 10000, 
					'Price_Max' => 40000, 
					'Hours_Start' => '10:00:00', 
					'Hours_Closed' => '23:00:00', 
					'Wifi' => 0, 
					'Reservation' => 0, 
					'Smoking_Area' => 1, 
					'Free_Parking' => 1,
    		],
    		[
    				'Resto_Name' => 'KFC Basuki Rahmat', 
					'Resto_Description' => 'Restoran fast food franchise yang menjual ayam krispi enak', 
					'Resto_Location' => 'Jl. Basuki Rahmat', 
					'Resto_City' => 'Jakarta', 
					'Type' => 1, 
					'Price_Min' => 10000, 
					'Price_Max' => 200000, 
					'Hours_Start' => '10:00:00', 
					'Hours_Closed' => '23:00:00', 
					'Wifi' => 1, 
					'Reservation' => 1, 
					'Smoking_Area' => 0, 
					'Free_Parking' => 0,
    		],
    		[
    				'Resto_Name' => 'Zangrandi', 
					'Resto_Description' => 'Restoran tempat jual es krim tempoe doeloe', 
					'Resto_Location' => 'Jl. Gandaria City', 
					'Resto_City' => 'Jakarta', 
					'Type' => 2, 
					'Price_Min' => 30000, 
					'Price_Max' => 150000, 
					'Hours_Start' => '10:00:00', 
					'Hours_Closed' => '23:00:00', 
					'Wifi' => 1, 
					'Reservation' => 0, 
					'Smoking_Area' => 1, 
					'Free_Parking' => 1,
    		],
    		[
    				'Resto_Name' => 'Bakso Mbledos', 
					'Resto_Description' => 'Restoran tempat jual bakso pedas enak', 
					'Resto_Location' => 'Jl. Thamrin', 
					'Resto_City' => 'Jakarta', 
					'Type' => 1, 
					'Price_Min' => 10000, 
					'Price_Max' => 30000, 
					'Hours_Start' => '10:00:00', 
					'Hours_Closed' => '22:00:00', 
					'Wifi' => 0, 
					'Reservation' => 0, 
					'Smoking_Area' => 1, 
					'Free_Parking' => 1,
    		],
    		[
    				'Resto_Name' => 'Wendys', 
					'Resto_Description' => 'Franchise fast food luar negeri yang menjual ayam krispi dan burger lezat', 
					'Resto_Location' => 'Jl. Garut', 
					'Resto_City' => 'Bandung', 
					'Type' => 3, 
					'Price_Min' => 10000, 
					'Price_Max' => 200000, 
					'Hours_Start' => '10:00:00', 
					'Hours_Closed' => '23:00:00', 
					'Wifi' => 1, 
					'Reservation' => 1, 
					'Smoking_Area' => 0, 
					'Free_Parking' => 0,
    		],
    		[
    				'Resto_Name' => 'Chimory', 
					'Resto_Description' => 'Tempat jual susu segar dan jajanan ringan yang enak', 
					'Resto_Location' => 'Jl. Puncak', 
					'Resto_City' => 'Bandung', 
					'Type' => 1, 
					'Price_Min' => 10000, 
					'Price_Max' => 100000, 
					'Hours_Start' => '09:00:00', 
					'Hours_Closed' => '20:00:00', 
					'Wifi' => 1, 
					'Reservation' => 1, 
					'Smoking_Area' => 1, 
					'Free_Parking' => 0,
    		],
    	]);
        //
    }
}
